apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: azure-managed-dynamic-disc
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: default
  resources:
    requests:
      storage: 1Gi
