apiVersion: v1
kind: Secret
metadata:
  name: backendsecret
type: Opaque
data:
  db: <<base64 encoded connectionstring here>>
  azurestorageaccountkey: <<base64 encoded SQL Azure Host here>>
  azurestorageaccountname: <<base64 encoded SQL Azure User here>>
  ai_key: <<base64 encoded AI Key>>
